### ISSUE TITLE
2.0.0 No Longer Supports PHP 5.6.x

### ISSUE THREAD

**Issue by willbuckner** [Sean-Der/pecl-web_services-oauth#2]
Hey guys,

[On StackOverflow](https://stackoverflow.com/questions/34937540/installing-oauth-pecl-package-on-php-5-on-os-x/34937578#34937578), I discovered that your 2.0.0 release no longer supports PHP <7.0 in `package.xml`. The changelog only mentions that support for PHP7 was added, not that 5.x support was removed. Is it possible to fix the requirements such that 5.5/5.6 still works, or does the code now depend on PHP7-only APIs?

Thanks!

**Comment by Sean-Der** [comment]
Hi @willbuckner 

2.0.0 only has PHP 7 support, and there is an open bug for `pecl` to install the newest compatible version [here](https://bugs.php.net/bug.php?id=71224)

Unfortunately I can't update the Changelogs for an already released version, but when I fix the inevitable bugs that come up I will make sure to mention it!
