### ISSUE TITLE
A new version should probably be released

### ISSUE THREAD

**Issue by di72nn** [Sean-Der/pecl-web_services-oauth#7]
It seems there is an issue (cweiske/grauphel#36) with current 2.0.0 PECL release, that was fixed in `master`.
Please consider releasing a new version.

Sorry if github is not an appropriate place for such request.

**Comment by Sean-Der** [comment]
Hey @di72nn 

This is the right place for requests! I will release a new version today, sorry for falling behind on this.

thanks

**Comment by Sean-Der** [comment]
After getting one last issue fixed, a [new version](https://pecl.php.net/package/oauth/2.0.1) is out!

Thanks for the patience
